export const GET_COLLEGE_DATA_REQUEST = "GET_COLLEGE_DATA_REQUEST";
export const GET_COLLEGE_DATA_RESPONSE = "GET_COLLEGE_DATA_RESPONSE";
export const ADD_OR_UPDATE_STUDENT_DETAILS_REQUEST = "ADD_OR_UPDATE_STUDENT_DETAILS_REQUEST";
export const ADD_OR_UPDATE_STUDENT_DETAILS_RESPONSE = "ADD_OR_UPDATE_STUDENT_DETAILS_RESPONSE";
export const DELETE_STUDENT_DETAILA_REQUEST = "DELETE_STUDENT_DETAILA_REQUEST";
export const DELETE_STUDENT_DETAILA_RESPONSE = "DELETE_STUDENT_DETAILA_RESPONSE";
export const ADD_BUTTON = "ADD_BUTTON";
export const SEARCH_KEY = "SEARCH_KEY"